### ISSUE TITLE
Ideas for v1.0

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/BiodiversityObservationNetworks.jl#27]
- Error handling
    - Each invalid call should throw an error of abstract type `BONException`
    - Have a documentation section for each subtype of `BONException` to enable user debugging
    
- Algorithms
    - cube sampling (refiner)
    - Environmental uniquness via KNN (seeder)
        -  Take the vector of layers at each cell in the raster and applies knn to each cell in the raster. choose the closest cell in the raster to the k cluster centers 
    - fractal triad, or some scale dependence thing, maybe

- Documentation
    - A tutorial section that gives background info not specific to the package for new users
    - Uniqueness vignette includes KNNUniqueness and has more text
    - Vignette on cube smapling

**Comment by karinorman** [comment]
Just because we were thinking about it today, we might want to build in stratification (whether as an option for individual sampling algorithms or a separate thing). Not sure if it needs to be v1.0.

**Comment by gottacatchenall** [comment]
this issue has been functionally replaced by the ongoing list of features being added in #65 (including general purpose stratification)
