### ISSUE TITLE
simplesdm inputs should give selected points in the CRS of the layer input

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/BiodiversityObservationNetworks.jl#36]

**Comment by tpoisot** [comment]
would lat/lon work, and then the user deals with them later on?

**Comment by gottacatchenall** [comment]
yeah that should be fine

**Comment by tpoisot** [comment]
as a note, geojson assumes points are in wgs84, and I think it's fine to do the same

**Comment by gottacatchenall** [comment]
this is resolved in the mess of #65
